-- Shule AI V6 chat/profile hotfix. Safe to run multiple times.

ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "groupId" VARCHAR(255);
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "classId" INTEGER;
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "type" VARCHAR(255) DEFAULT 'private';
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "schoolCode" VARCHAR(255);
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Messages" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "profileImage" TEXT;