ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "code" VARCHAR(255);
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "displayName" VARCHAR(255);
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "ownerType" VARCHAR(50) DEFAULT 'child';
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "price_kes" INTEGER DEFAULT 0;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "monthlyPriceKes" INTEGER;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "termlyPriceKes" INTEGER;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "yearlyPriceKes" INTEGER;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "setupFeeMinKes" INTEGER;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "setupFeeMaxKes" INTEGER;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "features" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "lockedFeatures" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "limits" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER DEFAULT 0;
ALTER TABLE "SubscriptionPlans" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;
ALTER TABLE "Subscriptions" ADD COLUMN IF NOT EXISTS "features" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "Subscriptions" ADD COLUMN IF NOT EXISTS "limits" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE "Subscriptions" ADD COLUMN IF NOT EXISTS "auditTrail" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "SubscriptionPayments" ADD COLUMN IF NOT EXISTS "auditTrail" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "Payments" ADD COLUMN IF NOT EXISTS "auditTrail" JSONB DEFAULT '[]'::jsonb;

UPDATE "SubscriptionPlans" SET "code"='child_essential', "name"='essential', "displayName"='Essential', "ownerType"='child', "price_kes"=100, "monthlyPriceKes"=100, "yearlyPriceKes"=1200, "features"='["marks","attendance","homework","timetable","basic_ai_tutor"]'::jsonb, "limits"='{"aiQuestionsPerMonth":30}'::jsonb, "sortOrder"=10, "isActive"=true, "updatedAt"=NOW() WHERE LOWER("name") IN ('basic','essential') OR LOWER(COALESCE("code",'')) IN ('basic','essential','child_essential');
UPDATE "SubscriptionPlans" SET "code"='child_smart', "name"='smart', "displayName"='Smart', "ownerType"='child', "price_kes"=250, "monthlyPriceKes"=250, "yearlyPriceKes"=3000, "features"='["marks","attendance","homework","timetable","ai_tutor","weak_subject_detection","study_recommendations"]'::jsonb, "limits"='{"aiQuestionsPerMonth":150}'::jsonb, "sortOrder"=11, "isActive"=true, "updatedAt"=NOW() WHERE LOWER("name") IN ('premium','smart') OR LOWER(COALESCE("code",'')) IN ('premium','smart','child_smart');
UPDATE "SubscriptionPlans" SET "code"='child_genius', "name"='genius', "displayName"='Genius', "ownerType"='child', "price_kes"=500, "monthlyPriceKes"=500, "yearlyPriceKes"=6000, "features"='["marks","attendance","homework","timetable","unlimited_ai_tutor","personalized_study_plan","exam_prep","advanced_insights"]'::jsonb, "limits"='{"aiQuestionsPerMonth":-1,"unlimitedAI":true}'::jsonb, "sortOrder"=12, "isActive"=true, "updatedAt"=NOW() WHERE LOWER("name") IN ('ultimate','genius') OR LOWER(COALESCE("code",'')) IN ('ultimate','genius','child_genius');

INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'child_essential','essential','Essential','child',100,100,1200,NULL,NULL,'["marks","attendance","homework","timetable","basic_ai_tutor"]'::jsonb,'[]'::jsonb,'{"aiQuestionsPerMonth":30}'::jsonb,10,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='child_essential');
INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'child_smart','smart','Smart','child',250,250,3000,NULL,NULL,'["marks","attendance","homework","timetable","ai_tutor","weak_subject_detection","study_recommendations"]'::jsonb,'[]'::jsonb,'{"aiQuestionsPerMonth":150}'::jsonb,11,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='child_smart');
INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'child_genius','genius','Genius','child',500,500,6000,NULL,NULL,'["marks","attendance","homework","timetable","unlimited_ai_tutor","personalized_study_plan","exam_prep","advanced_insights"]'::jsonb,'[]'::jsonb,'{"aiQuestionsPerMonth":-1,"unlimitedAI":true}'::jsonb,12,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='child_genius');
INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'school_starter','starter','Starter','school',5000,5000,50000,50000,100000,'["students","teachers","attendance","marks","reports","fees","homework","timetable","maintenance_included"]'::jsonb,'["school_branding","ai_analytics","smart_alerts","advanced_reports"]'::jsonb,'{"branding":false,"support":"basic"}'::jsonb,1,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='school_starter');
INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'school_growth','growth','Growth','school',10000,10000,100000,50000,100000,'["students","teachers","attendance","marks","reports","fees","homework","timetable","school_branding","advanced_analytics","smart_alerts","maintenance_included"]'::jsonb,'[]'::jsonb,'{"branding":true,"support":"priority"}'::jsonb,2,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='school_growth');
INSERT INTO "SubscriptionPlans" ("code","name","displayName","ownerType","price_kes","monthlyPriceKes","yearlyPriceKes","setupFeeMinKes","setupFeeMaxKes","features","lockedFeatures","limits","sortOrder","isActive","createdAt","updatedAt") SELECT 'school_enterprise','enterprise','Enterprise','school',30000,30000,300000,50000,100000,'["all_features"]'::jsonb,'[]'::jsonb,'{"branding":true,"support":"dedicated"}'::jsonb,3,true,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM "SubscriptionPlans" WHERE "code"='school_enterprise');

SELECT id, "code", "name", "displayName", "ownerType", "price_kes", "monthlyPriceKes" FROM "SubscriptionPlans" ORDER BY "ownerType", "sortOrder", id;
