ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "classId" INTEGER;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "curriculum" VARCHAR(255);
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'draft';
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN DEFAULT false;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "publishedBy" INTEGER;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "lockedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "unlockedBy" INTEGER;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "unlockReason" TEXT;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "auditTrail" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "AcademicRecords" ADD COLUMN IF NOT EXISTS "gradingScale" JSONB;
CREATE INDEX IF NOT EXISTS academicrecords_school_term_year_idx ON "AcademicRecords" ("schoolCode", "term", "year");
CREATE INDEX IF NOT EXISTS academicrecords_student_subject_idx ON "AcademicRecords" ("studentId", "subject");
