const express = require('express');
const { Op } = require('sequelize');
const { protect, authorize } = require('../middleware/auth');
const { User, Teacher, Student, Parent, Class, AcademicRecord, Attendance, School, Alert, Task, Payment } = require('../models');

const router = express.Router();
router.use(protect);

function ok(res, data = null, message = 'OK') { return res.json({ success: true, message, data }); }
function fail(res, status, message) { return res.status(status).json({ success: false, message }); }
function grade(score){ if(score == null) return null; const s=Number(score); if(s>=80) return 'EE'; if(s>=60) return 'ME'; if(s>=40) return 'AE'; return 'BE'; }
async function assertSchoolUser(user, schoolCode){ return user && (!schoolCode || user.schoolCode === schoolCode); }
async function teacherById(id, schoolCode){ return Teacher.findByPk(id, { include:[{ model:User, attributes:['id','name','email','phone','schoolCode','isActive','role'] }] }).then(t => t && t.User?.schoolCode === schoolCode ? t : null); }
async function studentById(id, schoolCode){ return Student.findByPk(id, { include:[{ model:User, attributes:['id','name','email','phone','schoolCode','isActive','role'] }] }).then(s => s && s.User?.schoolCode === schoolCode ? s : null); }

// ============ REAL MONEY DISABLED ============
function moneyDisabled(req,res){ return fail(res, 503, 'Real money collection is disabled in this national rollout school-operations build. Enable Daraja only after live payment audit.'); }
router.post('/payments/parent/fee/stk', moneyDisabled);
router.post('/payments/parent/subscription/stk', moneyDisabled);
router.post('/payments/admin/name-change/stk', moneyDisabled);
router.post('/payments/platform/stk', moneyDisabled);
router.post('/parent/pay', moneyDisabled);
router.post('/parent/upgrade-plan', moneyDisabled);
router.post('/subscription/upgrade', moneyDisabled);
router.post('/subscription/initiate-payment', moneyDisabled);

// ============ ADMIN COMPLETION ROUTES ============
router.post('/admin/teachers/:teacherId/activate', authorize('admin','super_admin'), async (req,res)=>{ try{ const t=await teacherById(req.params.teacherId, req.user.schoolCode); if(!t) return fail(res,404,'Teacher not found'); await t.User.update({ isActive:true }); await t.update({ approvalStatus:'approved', approvedBy:req.user.id, approvedAt:new Date() }); return ok(res,t,'Teacher activated successfully'); }catch(e){ return fail(res,500,e.message); } });
router.post('/admin/teachers/:teacherId/reactivate', authorize('admin','super_admin'), async (req,res)=>{ try{ const t=await teacherById(req.params.teacherId, req.user.schoolCode); if(!t) return fail(res,404,'Teacher not found'); await t.User.update({ isActive:true }); await t.update({ approvalStatus:'approved' }); return ok(res,t,'Teacher reactivated successfully'); }catch(e){ return fail(res,500,e.message); } });
router.post('/admin/teachers/:teacherId/deactivate', authorize('admin','super_admin'), async (req,res)=>{ try{ const t=await teacherById(req.params.teacherId, req.user.schoolCode); if(!t) return fail(res,404,'Teacher not found'); await t.User.update({ isActive:false }); await t.update({ approvalStatus:'suspended', duties:{ ...(t.duties||{}), lastDeactivationReason:req.body?.reason||'Deactivated by admin', deactivatedAt:new Date() } }); return ok(res,t,'Teacher deactivated successfully'); }catch(e){ return fail(res,500,e.message); } });
router.post('/admin/teachers/:teacherId/suspend', authorize('admin','super_admin'), async (req,res)=>{ try{ const t=await teacherById(req.params.teacherId, req.user.schoolCode); if(!t) return fail(res,404,'Teacher not found'); await t.User.update({ isActive:false }); await t.update({ approvalStatus:'suspended', duties:{ ...(t.duties||{}), suspensionReason:req.body?.reason||'Suspended by admin', suspendedAt:new Date() } }); return ok(res,t,'Teacher suspended successfully'); }catch(e){ return fail(res,500,e.message); } });

router.get('/admin/classes/:classId/students', authorize('admin','super_admin'), async (req,res)=>{ try{ const cls=await Class.findOne({ where:{ id:req.params.classId, schoolCode:req.user.schoolCode } }); if(!cls) return fail(res,404,'Class not found'); const where={ [Op.or]: [{ grade:cls.name }, { grade:cls.grade }] }; const students=await Student.findAll({ where, include:[{ model:User, where:{ schoolCode:req.user.schoolCode, role:'student' }, attributes:['id','name','email','phone','schoolCode'] }], order:[[User,'name','ASC']] }); return ok(res,students,'Class students loaded'); }catch(e){ return fail(res,500,e.message); } });
router.post('/admin/students/:studentId/expel', authorize('admin','super_admin'), async (req,res)=>{ try{ const s=await studentById(req.params.studentId, req.user.schoolCode); if(!s) return fail(res,404,'Student not found'); await s.update({ status:'transferred', academicStatus:'critical', preferences:{ ...(s.preferences||{}), exitType:'expelled', exitReason:req.body?.reason||'Expelled by admin', exitedAt:new Date() } }); await s.User.update({ isActive:false }); return ok(res,s,'Student removed from active roll'); }catch(e){ return fail(res,500,e.message); } });

// ============ PARENT/STUDENT ACADEMIC COMPLETION ROUTES ============
async function parentCanAccess(parentUserId, studentId){ const parent=await Parent.findOne({ where:{ userId:parentUserId }, include:[{ model:Student, as:'students', where:{ id:studentId }, required:false }] }); return !!(parent && parent.students && parent.students.length); }
async function academicSummary(studentId, schoolCode){ const records=await AcademicRecord.findAll({ where:{ studentId, schoolCode, isPublished:true }, order:[['year','DESC'],['term','DESC'],['subject','ASC']] }); const bySubject={}; for(const r of records){ bySubject[r.subject]=bySubject[r.subject]||[]; bySubject[r.subject].push(r); } const subjects=Object.entries(bySubject).map(([subject, rows])=>{ const avg=Math.round(rows.reduce((a,b)=>a+Number(b.score||0),0)/(rows.length||1)); return { subject, average:avg, grade:grade(avg), records:rows }; }); const overall=subjects.length?Math.round(subjects.reduce((a,b)=>a+b.average,0)/subjects.length):null; return { records, subjects, overallAverage:overall, overallGrade:grade(overall) }; }
router.get('/parent/child/:studentId/marks', authorize('parent'), async (req,res)=>{ try{ if(!await parentCanAccess(req.user.id, req.params.studentId)) return fail(res,403,'You are not linked to this child'); return ok(res, await academicSummary(req.params.studentId, req.user.schoolCode)); }catch(e){ return fail(res,500,e.message); } });
router.get('/parent/child/:studentId/class-performance', authorize('parent'), async (req,res)=>{ try{ if(!await parentCanAccess(req.user.id, req.params.studentId)) return fail(res,403,'You are not linked to this child'); const target=await studentById(req.params.studentId, req.user.schoolCode); const peers=await Student.findAll({ where:{ grade:target.grade }, include:[{ model:User, where:{ schoolCode:req.user.schoolCode, role:'student' }}] }); const ids=peers.map(p=>p.id); const rows=await AcademicRecord.findAll({ where:{ studentId:{[Op.in]:ids}, schoolCode:req.user.schoolCode, isPublished:true }}); const averages=ids.map(id=>{ const rr=rows.filter(r=>r.studentId===id); return { studentId:id, average: rr.length?Math.round(rr.reduce((a,b)=>a+Number(b.score||0),0)/rr.length):0 }; }).sort((a,b)=>b.average-a.average); const rank=averages.findIndex(x=>Number(x.studentId)===Number(req.params.studentId))+1; return ok(res,{ classSize:ids.length, rank:rank||null, averages }); }catch(e){ return fail(res,500,e.message); } });
router.get('/parent/child/:studentId/subject-performance', authorize('parent'), async (req,res)=>{ try{ if(!await parentCanAccess(req.user.id, req.params.studentId)) return fail(res,403,'You are not linked to this child'); const summary=await academicSummary(req.params.studentId, req.user.schoolCode); return ok(res, summary.subjects); }catch(e){ return fail(res,500,e.message); } });

router.get('/student/marks/all', authorize('student'), async (req,res)=>{ try{ const student=await Student.findOne({ where:{ userId:req.user.id } }); if(!student) return fail(res,404,'Student profile not found'); return ok(res, await academicSummary(student.id, req.user.schoolCode)); }catch(e){ return fail(res,500,e.message); } });
router.get('/student/class-performance', authorize('student'), async (req,res)=>{ try{ const student=await Student.findOne({ where:{ userId:req.user.id } }); if(!student) return fail(res,404,'Student profile not found'); req.params.studentId=student.id; const peers=await Student.findAll({ where:{ grade:student.grade }, include:[{ model:User, where:{ schoolCode:req.user.schoolCode, role:'student' }}] }); const ids=peers.map(p=>p.id); const rows=await AcademicRecord.findAll({ where:{ studentId:{[Op.in]:ids}, schoolCode:req.user.schoolCode, isPublished:true }}); const averages=ids.map(id=>{ const rr=rows.filter(r=>r.studentId===id); return { studentId:id, average: rr.length?Math.round(rr.reduce((a,b)=>a+Number(b.score||0),0)/rr.length):0 }; }).sort((a,b)=>b.average-a.average); return ok(res,{ classSize:ids.length, rank:averages.findIndex(x=>Number(x.studentId)===Number(student.id))+1, averages }); }catch(e){ return fail(res,500,e.message); } });
router.get('/student/subject-performance', authorize('student'), async (req,res)=>{ try{ const student=await Student.findOne({ where:{ userId:req.user.id } }); if(!student) return fail(res,404,'Student profile not found'); const summary=await academicSummary(student.id, req.user.schoolCode); return ok(res, summary.subjects); }catch(e){ return fail(res,500,e.message); } });
router.get('/student/gpa', authorize('student'), async (req,res)=>{ try{ const student=await Student.findOne({ where:{ userId:req.user.id } }); if(!student) return fail(res,404,'Student profile not found'); const s=await academicSummary(student.id, req.user.schoolCode); const gpa=s.overallAverage==null?null:Number((s.overallAverage/20).toFixed(2)); return ok(res,{ gpa, overallAverage:s.overallAverage, grade:s.overallGrade }); }catch(e){ return fail(res,500,e.message); } });

// ============ SUPER ADMIN COMPLETION ROUTES ============
router.get('/super-admin/users', authorize('super_admin'), async (req,res)=>{ try{ const users=await User.findAll({ attributes:['id','name','email','phone','role','schoolCode','isActive','createdAt'], order:[['createdAt','DESC']], limit:1000 }); return ok(res,users); }catch(e){ return fail(res,500,e.message); } });
router.get('/super-admin/metrics', authorize('super_admin'), async (req,res)=>{ try{ const [schools,users,teachers,students,parents]=await Promise.all([School.count(),User.count(),Teacher.count(),Student.count(),Parent.count()]); return ok(res,{ schools, users, teachers, students, parents, uptime:process.uptime(), node:process.version, timestamp:new Date().toISOString() }); }catch(e){ return fail(res,500,e.message); } });
router.get('/super-admin/logs', authorize('super_admin'), async (req,res)=>{ try{ const alerts=await Alert.findAll({ order:[['createdAt','DESC']], limit:100 }); return ok(res, alerts.map(a=>({ id:a.id, type:a.type, title:a.title, role:a.role, createdAt:a.createdAt }))); }catch(e){ return fail(res,500,e.message); } });
router.get('/super-admin/schools/:schoolId/stats', authorize('super_admin'), async (req,res)=>{ try{ const schoolCode=req.params.schoolId; const [teachers,students,parents,classes,alerts]=await Promise.all([User.count({where:{schoolCode,role:'teacher'}}),User.count({where:{schoolCode,role:'student'}}),User.count({where:{schoolCode,role:'parent'}}),Class.count({where:{schoolCode}}),Alert.count({where:{schoolCode}}).catch(()=>0)]); return ok(res,{ schoolCode, teachers, students, parents, classes, alerts }); }catch(e){ return fail(res,500,e.message); } });
router.get('/super-admin/requests/history', authorize('super_admin'), async (req,res)=>{ try{ return ok(res, []); }catch(e){ return fail(res,500,e.message); } });

module.exports = router;
