const express = require('express');
const router = express.Router();
const { protect, authorize } = require('../middleware/auth');
const ctrl = require('../controllers/subscriptionController');
router.get('/plans', protect, ctrl.getPlans);
router.get('/my-status', protect, authorize('parent','student','admin','teacher','super_admin'), ctrl.getMyStatus);
router.post('/upgrade', protect, authorize('parent'), ctrl.upgrade);
router.post('/initiate-payment', protect, authorize('parent'), ctrl.initiatePayment);
router.post('/manual-override', protect, authorize('super_admin'), ctrl.manualOverride);
router.post('/school/activate', protect, authorize('admin','super_admin'), ctrl.activateSchool);
module.exports = router;
