const { LegalDocument } = require('../models');
const DEFAULTS = {
  terms: {
    title: 'Shule AI Terms of Service', version: '2026.05.03', content: `Shule AI provides school-management, learning-support, communication, and analytics tools for schools, parents, teachers, and students. Users must provide accurate information, use the service lawfully, protect account credentials, and avoid uploading harmful or unlawful content. Schools are responsible for ensuring they have authority to upload and manage learner records and for assigning appropriate user roles. Parents and guardians are responsible for supervising learner use at home. Shule AI may process school and learner data only for providing the service, security, support, reporting, and product improvement in line with applicable data-protection obligations. Fees, subscriptions, and payment-related features are governed by the active plan and payment confirmation records in the platform. The service may restrict premium features when subscriptions expire, during non-payment, or where an account is suspended. Shule AI is not a replacement for professional teaching judgment, school governance, legal advice, medical advice, or official examination bodies. Schools remain responsible for verifying records, marks, timetables, fee balances, and communications before relying on them operationally. Users must report suspected unauthorized access immediately. Continued use means acceptance of these terms and the active privacy notice.`
  },
  privacy: {
    title: 'Shule AI Privacy Notice', version: '2026.05.03', content: `Shule AI processes account data, school data, learner records, academic records, attendance, payment references, communication records, device/session metadata, consent records, and learning activity data. Data is used to provide dashboards, school workflows, parent/student access, subscription enforcement, learning recommendations, security, auditability, support, and legal compliance. Child data is processed under school authorization and/or parent/guardian consent depending on the workflow. Access is role-based: super admins manage platform operations, school admins manage their school, teachers access assigned classes/subjects, parents access linked children, and students access their own learning records. Payment card or M-PESA PIN details are not stored by Shule AI; payment status, receipts, references, and transaction metadata may be stored for reconciliation. Users may request correction, access, or deletion where legally permitted, subject to school record-retention obligations. Security controls include authentication, role restrictions, audit trails, and subscription/state checks. Data may be retained as required for school operations, legal compliance, dispute resolution, and fraud prevention.`
  },
  child_data_consent: {
    title: 'Parent and School Child Data Consent', version: '2026.05.03', content: `By accepting, the school administrator and/or parent confirms that learner data may be processed in Shule AI for school administration, learning support, communication, analytics, performance tracking, payments, and child-specific recommendations. The school confirms it has authority to upload learner data and assign staff access. The parent/guardian confirms they understand that Shule AI may show learner progress, homework tasks, AI tutor interactions, and subscription-gated learning tools connected to their child. Consent can be reviewed or withdrawn where legally permitted, but withdrawal may limit access to features that require learner records.`
  },
  school_dpa: {
    title: 'School Data Processing Agreement Summary', version: '2026.05.03', content: `The school acts as the primary controller of school and learner records it uploads or manages. Shule AI acts as a service provider/processor for delivering the platform, securing the service, maintaining audit trails, and supporting users. Shule AI will process school data according to the school’s configuration and documented service purposes, restrict access by role, and maintain operational security safeguards. The school is responsible for lawful collection of learner data, notices to parents/guardians, staff role assignment, and record accuracy.`
  }
};
async function ensure(type){ const d=DEFAULTS[type]; const [row]=await LegalDocument.findOrCreate({ where:{type,version:d.version}, defaults:{...d,isActive:true} }); return row; }
exports.getActive = async (req,res)=>{ try{ const type=req.params.type; if(!DEFAULTS[type]) return res.status(400).json({success:false,message:'Unknown legal document type'}); let row=await LegalDocument.findOne({where:{type,isActive:true},order:[['effectiveAt','DESC']]}); if(!row) row=await ensure(type); res.json({success:true,data:row}); }catch(e){res.status(500).json({success:false,message:e.message});} };
exports.getAllActive = async (req,res)=>{ try{ const data={}; for(const type of Object.keys(DEFAULTS)){ let row=await LegalDocument.findOne({where:{type,isActive:true},order:[['effectiveAt','DESC']]}); if(!row) row=await ensure(type); data[type]=row; } res.json({success:true,data}); }catch(e){res.status(500).json({success:false,message:e.message});} };
exports.upsert = async (req,res)=>{ try{ if(req.user.role!=='super_admin') return res.status(403).json({success:false,message:'Forbidden'}); const {type}=req.params; const {title,version,content}=req.body; if(!DEFAULTS[type] && !['terms','privacy','school_dpa','child_data_consent'].includes(type)) return res.status(400).json({success:false,message:'Unknown legal document type'}); await LegalDocument.update({isActive:false},{where:{type}}); const row=await LegalDocument.create({type,title,version,content,isActive:true,effectiveAt:new Date()}); res.status(201).json({success:true,data:row}); }catch(e){res.status(500).json({success:false,message:e.message});} };
